[versions]
# SDK versions
compileSdk = "36"
minSdk = "24"
targetSdk = "36"

# Build tools
agp = "8.2.2"
kotlin = "1.9.0"

# AndroidX
appcompat = "1.7.1"
core = "1.17.0"

# Testing
junit = "4.13.2"
junitExt = "1.3.0"
espresso = "3.7.0"

# Other
zxing = "3.5.4"

[libraries]
# AndroidX
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

# Other
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
